#!/bin/bash

echo "🔧 TourEase Gemini AI Setup Guide"
echo "================================="
echo ""
echo "To enable dynamic, period-aware AI analytics in TourEase, you need to:"
echo ""
echo "1. Get a Google Gemini API Key:"
echo "   - Visit: https://makersuite.google.com/app/apikey"
echo "   - Sign in with your Google account"
echo "   - Click 'Create API Key'"
echo "   - Copy the generated key"
echo ""
echo "2. Add the API key to your .env file:"
echo "   - Open: server/.env"
echo "   - Replace 'your-gemini-api-key-here' with your actual API key"
echo "   - Save the file"
echo ""
echo "3. Restart the backend server:"
echo "   cd server"
echo "   npm run dev"
echo ""
echo "4. Test the integration:"
echo "   node test-periods.js"
echo ""
echo "Current API Key Status:"
if [ -z "$GEMINI_API_KEY" ] || [ "$GEMINI_API_KEY" = "your-gemini-api-key-here" ]; then
    echo "❌ API Key not configured or using placeholder"
    echo "   The system will use fallback data until you add a real API key"
else
    echo "✅ API Key appears to be configured"
    echo "   Key: ${GEMINI_API_KEY:0:8}..."
fi
echo ""
echo "📝 Note: The free tier has rate limits. If you see 429 errors,"
echo "   you may need to wait or upgrade to a paid plan."
